/**
 * VS3 — project-scoped voice-audio storage.
 *
 * Everything a project's cloned-voice workflow produces lives under the
 * project's OWN directory, next to its `project.json`:
 *
 *   data/projects/<videoId>/voice-audio/state.json           (references, assignments, previews, approvals)
 *   data/projects/<videoId>/voice-audio/references/<id>.wav  (approved reference recordings)
 *   data/projects/<videoId>/voice-audio/previews/<id>/seg-*.wav (generated narration artifacts)
 *
 * Conventions honoured (VS3 §4):
 *   - identifiers are generated server-side and validated against a strict
 *     pattern, so no client string ever reaches the filesystem;
 *   - every path is derived from a validated id under the project's own root and
 *     then re-checked for containment (defence in depth against traversal);
 *   - a path that resolves through a symlink outside the project root is
 *     refused;
 *   - state writes are atomic (temp file + rename), so an interrupted write can
 *     never leave a half-parsed state file;
 *   - deleting a reference deletes ONLY that reference's own file: the source
 *     upload is never shared and never re-used by another record;
 *   - failed generations remove their partial artifacts and never touch the
 *     reference recordings.
 */

import fs from 'node:fs';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import type {
  VoiceAudioApprovalRecord,
  VoiceAudioAssignment,
  VoiceAudioPreviewRecord,
  VoiceReferenceRecord,
} from '@buildtrack/core';
import { DATA_DIR, PROJECTS_DIR, projectDir } from './platform.js';

export const VOICE_AUDIO_DIR_NAME = 'voice-audio';
export const VOICE_AUDIO_STATE_FILE = 'state.json';
export const VOICE_AUDIO_REFERENCES_DIR = 'references';
export const VOICE_AUDIO_PREVIEWS_DIR = 'previews';

export const VOICE_AUDIO_STATE_VERSION = 1;

/** Maximum size of one reference recording: 64 MB (≈ 6 minutes of 48 kHz stereo). */
export const MAX_REFERENCE_UPLOAD_BYTES = 64 * 1024 * 1024;

/** Reference recordings longer than this are refused (a clone needs ~10 s). */
export const MAX_REFERENCE_DURATION_SECONDS = 120;

const REFERENCE_ID_RE = /^ref_[a-z0-9]{8,32}$/;
const PREVIEW_ID_RE = /^prv_[a-z0-9]{8,32}$/;

export interface VoiceAudioPersistedState {
  schemaVersion: number;
  /** Stored in the project file so a stale copy is detectable. */
  projectId: string;
  updatedAt: string;
  references: VoiceReferenceRecord[];
  assignments: VoiceAudioAssignment[];
  /** Only the CURRENT preview is kept (plus its status), to bound storage. */
  preview: VoiceAudioPreviewRecord | null;
  approval: VoiceAudioApprovalRecord | null;
  /** Identifier of the target this narration belongs to (defaults to `long`). */
  targetId: string;
}

export const ALLOWED_REFERENCE_EXTENSIONS = ['.wav', '.mp3', '.m4a', '.flac', '.ogg'] as const;

export function newVoiceAudioState(projectId: string): VoiceAudioPersistedState {
  return {
    schemaVersion: VOICE_AUDIO_STATE_VERSION,
    projectId,
    updatedAt: new Date().toISOString(),
    references: [],
    assignments: [],
    preview: null,
    approval: null,
    targetId: 'long',
  };
}

export function newReferenceId(): string {
  return `ref_${randomBytes(8).toString('hex')}`;
}

export function newPreviewId(): string {
  return `prv_${randomBytes(8).toString('hex')}`;
}

export function isSafeReferenceId(value: unknown): value is string {
  return typeof value === 'string' && REFERENCE_ID_RE.test(value);
}

export function isSafePreviewId(value: unknown): value is string {
  return typeof value === 'string' && PREVIEW_ID_RE.test(value);
}

/**
 * A project id is used as a DIRECTORY NAME. Ids are generated by the app, but
 * this guard refuses anything that is not a plain identifier so a crafted id can
 * never escape the projects root.
 */
export function isSafeVideoId(value: unknown): value is string {
  return typeof value === 'string' && /^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/.test(value);
}

export function voiceAudioRoot(videoId: string): string {
  if (!isSafeVideoId(videoId)) throw new Error(`Unsafe project id: ${String(videoId)}`);
  return path.join(projectDir(videoId), VOICE_AUDIO_DIR_NAME);
}

export function voiceAudioStatePath(videoId: string): string {
  return path.join(voiceAudioRoot(videoId), VOICE_AUDIO_STATE_FILE);
}

export function referencesDir(videoId: string): string {
  return path.join(voiceAudioRoot(videoId), VOICE_AUDIO_REFERENCES_DIR);
}

export function previewsDir(videoId: string): string {
  return path.join(voiceAudioRoot(videoId), VOICE_AUDIO_PREVIEWS_DIR);
}

export function previewDir(videoId: string, previewId: string): string {
  if (!isSafePreviewId(previewId)) throw new Error(`Unsafe preview id: ${String(previewId)}`);
  return path.join(previewsDir(videoId), previewId);
}

/**
 * Containment guard: the resolved path must be the root itself or inside it,
 * AND its real (symlink-resolved) form must also stay inside. Returns null when
 * it escapes — callers answer 400/404, never a filesystem path.
 */
export function resolveInsideProject(videoId: string, candidate: string): string | null {
  const root = path.resolve(voiceAudioRoot(videoId));
  const abs = path.resolve(candidate);
  if (abs !== root && !abs.startsWith(root + path.sep)) return null;
  const realRoot = fs.existsSync(root) ? fs.realpathSync(root) : root;
  const nearest = (() => {
    let current = abs;
    for (;;) {
      if (fs.existsSync(current)) return fs.realpathSync(current);
      const parent = path.dirname(current);
      if (parent === current) return current;
      current = parent;
    }
  })();
  if (nearest !== realRoot && !nearest.startsWith(realRoot + path.sep)) return null;
  return abs;
}

/** Repo-relative POSIX path (the adapters require relative, portable paths). */
export function toRepoRelative(absPath: string): string {
  const rel = path.relative(process.cwd(), absPath).split(path.sep).join('/');
  if (!rel || rel.startsWith('..') || path.isAbsolute(rel)) {
    throw new Error(
      'The voice-audio storage root must live inside the repository so synthesis targets stay portable. ' +
        'Configure BUILDTRAKE_DATA inside the repository.'
    );
  }
  return rel;
}

export function loadVoiceAudioState(videoId: string): VoiceAudioPersistedState {
  const file = voiceAudioStatePath(videoId);
  if (!fs.existsSync(file)) return newVoiceAudioState(videoId);
  const raw = JSON.parse(fs.readFileSync(file, 'utf8')) as Partial<VoiceAudioPersistedState>;
  if (raw?.schemaVersion !== VOICE_AUDIO_STATE_VERSION) {
    /* Unknown version: do not guess. Start clean but keep the files on disk. */
    return newVoiceAudioState(videoId);
  }
  return {
    schemaVersion: VOICE_AUDIO_STATE_VERSION,
    projectId: videoId,
    updatedAt: typeof raw.updatedAt === 'string' ? raw.updatedAt : new Date().toISOString(),
    references: Array.isArray(raw.references) ? (raw.references as VoiceReferenceRecord[]) : [],
    assignments: Array.isArray(raw.assignments) ? (raw.assignments as VoiceAudioAssignment[]) : [],
    preview: (raw.preview ?? null) as VoiceAudioPreviewRecord | null,
    approval: (raw.approval ?? null) as VoiceAudioApprovalRecord | null,
    targetId: typeof raw.targetId === 'string' ? raw.targetId : 'long',
  };
}

export function saveVoiceAudioState(state: VoiceAudioPersistedState): void {
  if (!isSafeVideoId(state.projectId)) throw new Error(`Unsafe project id: ${state.projectId}`);
  const root = voiceAudioRoot(state.projectId);
  fs.mkdirSync(root, { recursive: true });
  const next: VoiceAudioPersistedState = {
    ...state,
    schemaVersion: VOICE_AUDIO_STATE_VERSION,
    updatedAt: new Date().toISOString(),
  };
  const file = voiceAudioStatePath(state.projectId);
  const tmp = `${file}.tmp-${process.pid}-${randomBytes(4).toString('hex')}`;
  fs.writeFileSync(tmp, JSON.stringify(next, null, 2), 'utf8');
  fs.renameSync(tmp, file);
}

export function findReference(
  state: VoiceAudioPersistedState,
  referenceId: string
): VoiceReferenceRecord | null {
  if (!isSafeReferenceId(referenceId)) return null;
  return state.references.find((r) => r.referenceId === referenceId) ?? null;
}

/** Absolute path of a stored reference file, contained inside the project root. */
export function referenceAbsPath(videoId: string, record: VoiceReferenceRecord): string | null {
  if (!record?.storedRef) return null;
  const abs = resolveInsideProject(videoId, path.join(process.cwd(), record.storedRef));
  return abs;
}

/** Delete ONLY the stored reference file; the directory is left intact. */
export function deleteReferenceFile(videoId: string, record: VoiceReferenceRecord): void {
  const abs = referenceAbsPath(videoId, record);
  if (!abs) return;
  try {
    if (fs.existsSync(abs) && fs.statSync(abs).isFile()) fs.unlinkSync(abs);
  } catch {
    /* Best effort: the state no longer references it either way. */
  }
}

/** Remove a preview's artifacts (used on regeneration and on failure cleanup). */
export function deletePreviewArtifacts(videoId: string, previewId: string | null | undefined): void {
  if (!previewId || !isSafePreviewId(previewId)) return;
  const dir = previewDir(videoId, previewId);
  const contained = resolveInsideProject(videoId, dir);
  if (!contained) return;
  try {
    fs.rmSync(contained, { recursive: true, force: true });
  } catch {
    /* Best effort. */
  }
}

/** Remove every preview directory that is not the current one. */
export function pruneOtherPreviews(videoId: string, keepPreviewId: string | null): void {
  const dir = previewsDir(videoId);
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir)) {
    if (entry === keepPreviewId) continue;
    if (!isSafePreviewId(entry)) continue;
    deletePreviewArtifacts(videoId, entry);
  }
}

/** Removes only temporary/partial files (`.tmp_*`) inside the project root. */
export function cleanupTempArtifacts(videoId: string): number {
  let removed = 0;
  const walk = (dir: string): void => {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.name.startsWith('.tmp_')) {
        try {
          fs.unlinkSync(full);
          removed += 1;
        } catch {
          /* best effort */
        }
      }
    }
  };
  walk(voiceAudioRoot(videoId));
  return removed;
}

/**
 * Is this reference id assigned to any speaker? Used to refuse a removal that
 * would silently leave a speaker with no voice (the assignment must be changed
 * first, or the removal must clear it explicitly).
 */
export function isReferenceAssigned(state: VoiceAudioPersistedState, referenceId: string): boolean {
  return state.assignments.some((a) => a.referenceId === referenceId);
}

/** Absolute path of the managed narration artifact of the CURRENT preview. */
export function previewArtifactAbsPath(
  videoId: string,
  preview: VoiceAudioPreviewRecord | null
): string | null {
  if (!preview?.artifactRef || !isSafePreviewId(preview.previewId)) return null;
  const expectedDir = path.resolve(previewDir(videoId, preview.previewId));
  const abs = resolveInsideProject(videoId, path.join(process.cwd(), preview.artifactRef));
  if (!abs) return null;
  /* The artifact must live inside ITS OWN preview directory. */
  if (!abs.startsWith(expectedDir + path.sep)) return null;
  return abs;
}
