#!/usr/bin/env bash
#
# Publish the demo MP4 deliverables to a DRAFT GitHub Release.
#
# WHY THIS IS A SEPARATE SCRIPT
# -----------------------------
# The sandbox this project was built in cannot reach uploads.github.com, so the
# MP4s could not be uploaded from here. `gh release create --draft` works (it
# talks to api.github.com), but the asset upload step posts to
# uploads.github.com and fails with EOF.
#
# Everything the upload needs is committed to the repository instead:
#   EVIDENCE/deliverables-manifest.txt  - every file, byte size, SHA-256
#   EVIDENCE/ffprobe.txt                - dimensions/codec/duration of each file
# and the files themselves are reproduced by `npm run demo`.
#
# Run this from a machine with normal GitHub access:
#
#     bash tools/publish-demo-assets.sh
#
# It creates the draft release, uploads every MP4, verifies each asset came
# back, and leaves the release UNPUBLISHED (draft) for a human to review.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO="${GH_REPO:-engmelkhabery1982/Video-Factory}"
TAG="${1:-demo-render-$(git rev-parse --short HEAD)}"

if ! command -v gh >/dev/null 2>&1; then
  echo "error: the GitHub CLI (gh) is required" >&2
  exit 1
fi

if [ ! -d output ]; then
  echo "error: no output/ directory. Run 'npm run demo' first." >&2
  exit 1
fi

mapfile -t FILES < <(find output -name '*.mp4' -type f | sort)

if [ ${#FILES[@]} -eq 0 ]; then
  echo "error: no .mp4 files under output/. Run 'npm run demo' first." >&2
  exit 1
fi

echo "About to upload ${#FILES[@]} file(s) to draft release '$TAG' in $REPO"
echo
total=0
for f in "${FILES[@]}"; do
  sz=$(stat -c%s "$f")
  total=$((total + sz))
  printf '  %-58s %8.1f MB\n' "$f" "$(echo "scale=1; $sz / 1048576" | bc)"
done
printf '  %-58s %8.1f MB\n' "TOTAL" "$(echo "scale=1; $total / 1048576" | bc)"
echo

read -r -p "Continue and create a DRAFT (not published) release? [y/N] " ok
[ "$ok" = "y" ] || { echo "aborted"; exit 1; }

if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
  echo "release '$TAG' already exists, adding assets to it"
else
  gh release create "$TAG" --repo "$REPO" --draft \
    --title "Demo render $TAG" \
    --notes "Long and Short exports for the three BuildTrack demo projects.

Generated by 'npm run demo'. Dimensions, codecs, durations and SHA-256
checksums are recorded in EVIDENCE/ffprobe.txt and
EVIDENCE/deliverables-manifest.txt in the repository.

This release is a DRAFT and has deliberately not been published."
fi

for f in "${FILES[@]}"; do
  echo "  uploading $f"
  gh release upload "$TAG" "$f" --repo "$REPO" --clobber
done

echo
echo "Verifying uploaded assets..."
gh release view "$TAG" --repo "$REPO" --json assets --jq '.assets[] | "  \(.name)  \(.size) bytes  \(.state)"'

echo
echo "Done. Release '$TAG' is a DRAFT - publish it from the GitHub Releases page when ready."
